CREATE TABLE IF NOT EXISTS USUARIO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    logradouro VARCHAR(100),
    bairro VARCHAR(100),
    numero VARCHAR(10),
    CEP VARCHAR(8)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS INSTITUICAO (
    USUARIO_id INT PRIMARY KEY,
    CNPJ VARCHAR(14) NOT NULL,
    site VARCHAR(100),
    CONSTRAINT fk_instituicao_usuario FOREIGN KEY (USUARIO_id) REFERENCES USUARIO(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PESSOA_FISICA (
    USUARIO_id INT PRIMARY KEY,
    CPF VARCHAR(11) NOT NULL,
    data_nascimento DATE,
    CONSTRAINT fk_pessoa_fisica_usuario FOREIGN KEY (USUARIO_id) REFERENCES USUARIO(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS LOCAL_DOACAO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(45) NOT NULL,
    logradouro VARCHAR(100),
    bairro VARCHAR(100),
    numero VARCHAR(10),
    CEP VARCHAR(8)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CAMPANHA_DOACAO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    INSTITUICAO_USUARIO_id INT NOT NULL,
    titulo VARCHAR(100) NOT NULL,
    descricao TEXT,
    url_imagem_capa VARCHAR(255),
    data_inicio DATE,
    data_fim DATE,
    status VARCHAR(20) DEFAULT 'ATIVA',
    itens_foco VARCHAR(200),
    meta_voluntarios INT,
    CONSTRAINT fk_campanha_instituicao FOREIGN KEY (INSTITUICAO_USUARIO_id) REFERENCES INSTITUICAO(USUARIO_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CAMPANHA_LOCAL_DOACAO (
    CAMPANHA_DOACAO_id INT NOT NULL,
    LOCAL_DOACAO_id INT NOT NULL,
    PRIMARY KEY (CAMPANHA_DOACAO_id, LOCAL_DOACAO_id),
    CONSTRAINT fk_campanha_local_campanha FOREIGN KEY (CAMPANHA_DOACAO_id) REFERENCES CAMPANHA_DOACAO(id) ON DELETE CASCADE,
    CONSTRAINT fk_campanha_local_local FOREIGN KEY (LOCAL_DOACAO_id) REFERENCES LOCAL_DOACAO(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DOACAO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    doador_id INT NULL,
    donatario_id INT NULL,
    LOCAL_DOACAO_id INT NULL,
    CONSTRAINT fk_doacao_doador FOREIGN KEY (doador_id) REFERENCES USUARIO(id) ON DELETE SET NULL,
    CONSTRAINT fk_doacao_donatario FOREIGN KEY (donatario_id) REFERENCES USUARIO(id) ON DELETE SET NULL,
    CONSTRAINT fk_doacao_local FOREIGN KEY (LOCAL_DOACAO_id) REFERENCES LOCAL_DOACAO(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ITEM (
    nome VARCHAR(45) NOT NULL,
    DOACAO_id INT NOT NULL,
    quantidade INT,
    descricao VARCHAR(200),
    motivo VARCHAR(200),
    e_novo VARCHAR(1),
    categoria VARCHAR(45),
    PRIMARY KEY (nome, DOACAO_id),
    CONSTRAINT fk_item_doacao FOREIGN KEY (DOACAO_id) REFERENCES DOACAO(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AVALIACAO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    data_avaliacao DATE,
    comentario VARCHAR(200),
    nota INT,
    papel_avaliador VARCHAR(45),
    DOACAO_id INT NOT NULL,
    CONSTRAINT fk_avaliacao_doacao FOREIGN KEY (DOACAO_id) REFERENCES DOACAO(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS INTERESSE (
    USUARIO_id INT NOT NULL,
    DOACAO_id INT NOT NULL,
    PRIMARY KEY (USUARIO_id, DOACAO_id),
    CONSTRAINT fk_interesse_usuario FOREIGN KEY (USUARIO_id) REFERENCES USUARIO(id) ON DELETE CASCADE,
    CONSTRAINT fk_interesse_doacao FOREIGN KEY (DOACAO_id) REFERENCES DOACAO(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS VAGA_VOLUNTARIO (
    CAMPANHA_DOACAO_id INT NOT NULL,
    codigo_vaga INT NOT NULL,
    data_inicio DATE,
    data_fim DATE,
    quantidade_vagas INT,
    descricao_atividades VARCHAR(200),
    carga_horaria_semanal INT,
    funcao VARCHAR(45),
    PRIMARY KEY (CAMPANHA_DOACAO_id, codigo_vaga),
    CONSTRAINT fk_vaga_campanha FOREIGN KEY (CAMPANHA_DOACAO_id) REFERENCES CAMPANHA_DOACAO(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS INSCRICAO (
    PESSOA_FISICA_USUARIO_id INT NOT NULL,
    VAGA_VOLUNTARIO_codigo_vaga INT NOT NULL,
    VAGA_VOLUNTARIO_CAMPANHA_DOACAO_id INT NULL,
    data DATE,
    status VARCHAR(45),
    PRIMARY KEY (PESSOA_FISICA_USUARIO_id, VAGA_VOLUNTARIO_codigo_vaga),
    CONSTRAINT fk_inscricao_pessoa FOREIGN KEY (PESSOA_FISICA_USUARIO_id) REFERENCES PESSOA_FISICA(USUARIO_id) ON DELETE CASCADE,
    CONSTRAINT fk_inscricao_vaga FOREIGN KEY (VAGA_VOLUNTARIO_CAMPANHA_DOACAO_id, VAGA_VOLUNTARIO_codigo_vaga) REFERENCES VAGA_VOLUNTARIO(CAMPANHA_DOACAO_id, codigo_vaga) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
